window.BLOCKS_DATA = [
  {
    id: 1,
    title: "Ekonomi – Pengar och vardag",
    icon: "coins",
    subject: "Ekonomi",
    sections: [
      {
        title: "Sida 42: Ekonomi",
        page: "42",
        track: "Båda",
        core: true,
        text: "Ekonomi\n\nVad händer med de pengar som du och din familj arbetat ihop? En del försvinner i skatt. Staten och kommunen tar in skatt som går till löner för lärare och räddningstjänstens personal med mera.\n\nHär får du lära dig hur mycket ungefär det kostar att leva och hur man får ekonomin att gå ihop. När du har läst avsnittet förstår du också varför de första jordgubbarna på våren är mycket dyrare än jordgubbarna lite längre fram.\n\nLäs om\n\npengars funktion i samhället.\n\nfamiljers inkomster och utgifter.\nvad en budget är och hur du kan göra en egen budget.\n\nom den offentliga sektorn (kommunerna, regionerna och staten).\n\nhur pengarna cirkulerar i det ekonomiska kretsloppet.",
        concepts: ["Ekonomi", "Skatt", "Välfärd"],
        mustKnow: ["Att skatt går till gemensamma löner", "Vad kapitlet innehåller"],
        summary: ["Skatten betalar lärare och räddningstjänst", "Ekonomi handlar om balans mellan inkomster och utgifter"],
        test: [{ q: "Vart går en del av pengarna vi tjänar?", a: "Till skatt" }],
        reasoning: "Varför betalar vi skatt istället för att betala allt privat?",
        application: "Titta på tre saker i ditt klassrum. Hur har de betalats?"
      },
      {
        title: "Sida 43: Vad är pengar?",
        page: "43",
        track: "Båda",
        core: true,
        text: "Vad är pengar?\n\nSkulle vi klara oss utan pengar? Ja, men det blir besvärligt, även om byteshandel förekommit så länge människan har funnits. För några tusen år sedan uppfanns pengar.\n\nVad är då pengar? Mynt och sedlar kallas kontanter, men de är bara en liten del av alla pengar som finns. De allra flesta pengarna finns bara som elektroniska pengar. När du använder ett betalkort i en affär ger du till exempel affären rätt att ta ut pengar från ditt bankkonto. Du ser aldrig de här pengarna. Alla betalningar mellan företag sker på det här sättet. Även privatpersoner betalar de flesta räkningarna med elektroniska pengar, till exempel med betalkort eller genom att swisha.\n\nMynt blir sedlar\n\nDe äldsta svenska mynten var i metall och metallen skulle vara lika mycket värd som det stod på myntet. För 1 riksdaler silvermynt skulle man alltså kunna gå till en silversmed och få silver för 1 riksdaler. Men på 1600-talet blev det brist på guld och silver, och då tog man till koppar, som ju var billigare. Men då blev mynten större och tyngre. De allra tyngsta mynten vägde över 19 kilo och de fick dras på skottkärra!\n\nPå 1660-talet öppnade en smart köpman i Stockholm, Johan Palmstruch, en bank och tog emot koppar, silver och guld för förvaring. Kunderna fick ett kvitto på att de lämnat in metall till ett visst värde. De här kvittona blev de första sedlarna.",
        concepts: ["Kontanter", "Elektroniska pengar", "Johan Palmstruch"],
        mustKnow: ["Att pengar förr var tunga", "Att de flesta pengar idag är digitala"],
        summary: ["De tyngsta mynten vägde 19 kg", "Johan Palmstruch skapade de första sedlarna"],
        test: [{ q: "Vad vägde de tyngsta svenska mynten?", a: "Över 19 kilo" }],
        reasoning: "Varför är det bättre med digitala pengar än kopparplåtar?",
        application: "Har du testat att swisha? Hur fungerar det?"
      },
      {
        title: "Sida 44: Pengarnas värde",
        page: "44",
        track: "Båda",
        core: true,
        text: "Pengarnas värde\n\nMånga som var i din ålder åren kring 1960 fick två kronor i veckopeng. Men de pengarna räckte till både bio och 10 femöreskolor. Idag kostar det mycket mer att gå på bio. Men som tur var har också veckopengen ökat, för troligen får du mer än två kronor i veckopeng. När Pippi Långstrump hade premiär 1973 kostade biobiljetten ungefär 5 kronor.\n\nMen det är inte bara bio som blivit dyrare i Sverige. Allt har blivit dyrare. När priserna stiger säger ekonomerna att det är inflation. Idag räcker inte två kronor till mycket. Två kronor är mycket mindre värda idag än för 60 år sedan. Inflationen under senare år har legat på ungefär 2% om året. Vi tänker oss att lunchpriset på en restaurang den 1 januari är 100 kronor. Om lunchpriset har en inflation på 2% kostar lunchen 102 kronor ett år senare.\n\nDe vuxna har alltid känt till inflationen eftersom de vill ha högre lön när det är inflation, när allt blir dyrare. Under alla åren har fackföreningarna sett till att lönerna har stigit. Idag har till exempel en industriarbetare 12 gånger högre lön än 1970, men kan ändå inte köpa så väldigt mycket mer för lönen än man kunde då.",
        concepts: ["Inflation", "Värde", "Veckopeng"],
        mustKnow: ["Vad inflation betyder", "Att priser stiger över tid"],
        summary: ["Inflation betyder att priser stiger och pengar blir mindre värda", "Bio kostade 5 kr år 1973"],
        test: [{ q: "Vad kallas det när allt blir dyrare?", a: "Inflation" }],
        reasoning: "Varför vill fackföreningar ha högre lön vid inflation?",
        application: "Fråga en äldre släkting vad en mjölk kostade när de var barn."
      },
      {
        title: "Sida 45: Inkomster och utgifter",
        page: "45",
        track: "Båda",
        core: true,
        text: "Inkomster och utgifter\n\nDet är skönt att få lön, men när månaden gått är pengarna nästan slut. Låtsasfamiljen Jonsson i Umeå får illustrera de inkomster och utgifter som väldigt många familjer har.\n\nLön och arbete\n\nAlla som är anställda i ett företag, eller i kommunen eller regionen, får lön för sitt jobb. Från lönen dras det skatt, inkomstskatt. Vi tänker oss rörmokaren Jan Jonsson som är anställd i Rörfirman Skruv & Böj i Umeå. Jan tjänar 30 000 kr i månaden. Men ungefär 30% går i skatt. Det är alltså 9 000 kr som Skruv & Böj varje månad skickar in till Skatteverket, där pengarna sätts in på Jonssons konto. Han får alltså ut 21 000 kr i lön. Jans fru Elsa kör en av kommunens sopbilar. Även hon får lön, och betalar skatt.\n\nAndra inkomster\n\nMen familjen Jonsson har även andra inkomster. Elsa har pengar insatta på banken och får ränta på dessa pengar. It är inte mycket pengar, eftersom räntan är så låg, inte ens 1 procent. Elsa och Jan har tre barn, 16-åriga Linn som går på gymnasiet och de 5-åriga tvillingarna Inez och Lia. Linn får 1 250 kr i studiebidrag eftersom hon har fyllt 16 år och bedriver heltidsstudier. (Hon skolkar inte heller för då kan studiebidraget dras in). När hon blir 18 år kommer studiebidraget in på konto och hon får studiebidrag till 20-årsdagen.\n\nFör tvillingarna Inez och Lia får föräldrarna barnbidrag, 1 250 kronor vardera i månaden. Dessutom får föräldrarna flerbarnstillägg.\n\nElsa var sjukskriven i tre veckor efter en arbetsskada. Under den tiden fick hon sjukersättning från Försäkringskassan. Elsa och Jan har ansökt om bostadsbidrag från Umeå kommun, alltså hjälp med hyran. Men kommunen sade nej eftersom Elsa och Jan tjänar för mycket.\n\nDin inkomst - månadspeng\n\nMånga barn och ungdomar får veckopeng eller månadspeng. Swedbank har gjort samma undersökning vart femte år och har kommit fram till att veckopengen och månadspengen har ökat. Två av tre barn och ungdomar har berättat för intervjupersonen att de måste göra något arbete hemma för att få pengarna.",
        concepts: ["Lön", "Barnbidrag", "Studiebidrag", "Sjukersättning"],
        mustKnow: ["Att skatten dras innan man får ut lönen", "Exempel på olika bidrag"],
        summary: ["Inkomster består av lön och bidrag", "Skatten är ofta ca 30%"],
        test: [{ q: "Vad kallas lönen efter skatt?", a: "Nettolön" }],
        reasoning: "Varför får man studiebidrag i gymnasiet?",
        application: "Räkna ut familjen Jonssons totala barnbidrag för tvillingarna."
      },
      {
        title: "Sida 46: Arbetsuppgifter hemma",
        page: "46",
        track: "Båda",
        core: true,
        text: "Bankerna ger ungdomarna möjlighet att öppna eget konto. Villkoret är ofta att någon förälder följer med till banken och skriver på en blankett som visar att föräldrarna godkänner att barnet har eget bankkonto. Ibland måste också föräldern vara kund i samma bank. Undersökningen visar också att osämjan om fickpengarna är störst i de familjer där pengarna utbetalas då och då, och inte regelbundet.\n\nArbetsuppgifter som ungdomarna hjälper till med hemma\n\nSwedbank Privatekonomi har undersökt vilka arbetsuppgifter som flickor och pojkar gör hemma. Det totala antalet flickor och pojkar som besvarat frågan står längst ned, 372 och 376 men talen visas i procent. För att ta ett exempel: 69% av flickorna (69 av 100 flickor) städar det egna rummet, medan endast 62% av pojkarna gör det.\n\nStäda egna rummet: Flickor 69%, Pojkar 62%\nDiska, dammsuga, vattna blommor: Flickor 58%, Pojkar 53%\nSkotta snö, trädgårdsarbete: Flickor 12%, Pojkar 25%\nTa hand om syskon: Flickor 15%, Pojkar 14%\nTa hand om husdjur: Flickor 35%, Pojkar 25%\nLäxor: Flickor 50%, Pojkar 51%",
        concepts: ["Statistik", "Procent", "Vårdnadshavare"],
        mustKnow: ["Att man behöver föräldrars lov för bankkonto", "Vem som gör mest hemma enligt undersökningen"],
        summary: ["De flesta ungdomar städar sitt rum", "Pojkar skottar oftare snö än flickor"],
        test: [{ q: "Hur många procent av flickorna städar rummet?", a: "69%" }],
        reasoning: "Varför tror du att pojkarna skottar mer snö än flickorna i statistiken?",
        application: "Gör en egen undersökning i klassen om vem som diskar hemma."
      },
      {
        title: "Sida 47: Vad kostar det att leva?",
        page: "47",
        track: "Båda",
        core: true,
        text: "Vad kostar det att leva?\n\nHushållsutgifter (Kostnad per månad):\nMat (all mat lagas hemma utom lunch vardagar): 2 250 kr\nFörbrukningsvaror: 70 kr\nHemutrustning: 240 kr\nMedier: 550 kr\nHyra: 2 270 kr\nHemförsäkring: 40 kr\nSumma hushållsutgifter: 5 420 kr\n\nÖvriga utgifter:\nPersonlig hygien: 700 kr\nKläder och skor: 520 kr\nFritid: 660 kr\nMobil: 150 kr\nÄta lunch ute (20 gånger i månaden): 1960 kr\nResor med lokaltrafik: 600 kr\nMedlemskapet i facket och i a-kassan: 510 kr\nSumma övriga utgifter: 5 100 kr\n\nTotala utgifter: 10 520 kr\n\nKälla: Konsumentverket (2021).\n\nAKTIVITET - Höj månadspengen\nI denna övningen ska du ta fram bra argument för varför du ska ha högre månadspeng.\n\n1. Gör en lista på saker som du inte gör, men som du kan tänka dig göra för att få högre månadspeng.\n2. Sätt pris på de olika punkterna.\n3. Fundera på vad dina föräldrar tycker är tråkigast.\n4. Kanske tycker du det är roligare? Där får du bäst betalt.\n5. Dela upp marknaden med syskon.",
        concepts: ["Kostnad", "Argument", "Konsumentverket"],
        mustKnow: ["Vad som är stora utgifter för en vuxen", "Hur man argumenterar för sin sak"],
        summary: ["Att leva som vuxen kostar ca 10 000 kr i månaden", "Mat och hyra är de största posterna"],
        test: [{ q: "Vad är totalkostnaden i exemplet?", a: "10 520 kr" }],
        reasoning: "Varför är det viktigt att veta vad saker kostar innan man flyttar hemifrån?",
        application: "Välj en syssla hemma. Vad tycker du den ska vara värd?"
      }
    ]
  },
  {
    id: 2,
    title: "Ekonomi – Samhälle och marknad",
    icon: "bar-chart-3",
    subject: "Ekonomi",
    sections: [
      {
        title: "Sida 48: Att göra en budget",
        page: "48",
        track: "Båda",
        core: true,
        text: "Budget? Det blir inte mer pengar för att man gör en tabell.\n\nAtt göra en budget\n\nAlla företag har samma grundregel: \"det måste gå runt\"! Det betyder att företagets utgifter måste vara mindre än företagets inkomster. Alla företag gör en budget vilket betyder att de beräknar, uppskattar, de närmaste månadernas utgifter och inkomster.\n\nOm utgifterna någon månad är större än inkomsterna gör det nog inget. Men det får inte vara så månad efter månad. Då måste företaget låna pengar. Och det vet vi ju, att låna kostar pengar, nämligen ränta. Om skulderna är så stora att företaget inte kan betala igen lånet kommer företaget att gå i konkurs och måste stänga.\n\nDin ekonomi liknar företagens ekonomi. Dina utgifter får inte vara större än de inkomster du har. Därför är det bra också för dig att göra en budget. Kanske ser den ut så här:\n\nAlis budget (Augusti)\nInkomster:\nMånadspeng 150 kr\nGåva från mormor 40 kr\nLön för kattvakt 60 kr\nSumma inkomster: 250 kr\n\nUtgifter:\nGodis 50 kr\nBio 100 kr\nMobilen 50 kr\nSpara 50 kr\nSumma utgifter: 250 kr",
        concepts: ["Budget", "Konkurs", "Utgift"],
        mustKnow: ["Att utgifterna inte får vara större än inkomsterna", "Vad en budget är"],
        summary: ["En budget är en plan för pengar", "Om pengarna inte räcker kan man gå i konkurs"],
        test: [{ q: "Vad händer om utgifterna är större än inkomsterna länge?", a: "Man går i konkurs" }],
        reasoning: "Varför är det bra att ha en post för 'spara' i sin budget?",
        application: "Gör en egen budget för nästa vecka med 50 kr."
      },
      {
        title: "Sida 49: Hållplats 1 Ekonomi",
        page: "49",
        track: "Båda",
        core: true,
        text: "SAMMANFATTNING\n\n• Pengar är mynt, sedlar och elektroniska pengar.\n• När priserna stiger kallas det inflation.\n• Alla som arbetar får lön och från lönen dras inkomstskatt.\n• Alla familjer som har barn under 16 år får barnbidrag, är du äldre får du studiebidrag.\n• Den som lånar ut pengar får ränta och den som lånar pengar betalar ränta.\n• Såväl företagens som familjernas och din ekonomi måste \"gå runt\", det vill säga utgifterna får inte vara större än inkomsterna.\n\nVIKTIGA ORD\nbyteshandel, pengar, kontanter, elektroniska pengar, lön, inkomstskatt, ränta, inflation, studiebidrag, budget, konkurs.",
        concepts: ["Inflation", "Byteshandel", "Sammanfattning"],
        mustKnow: ["Alla sammanfattningspunkter", "De viktiga orden"],
        summary: ["Här repeteras grunderna i ekonomi"],
        test: [{ q: "Vad kallas betalning efter 16 år för studier?", a: "Studiebidrag" }],
        reasoning: "Vilket av orden i listan är svårast att förstå? Varför?",
        application: "Skriv en mening som innehåller orden 'lön' och 'budget'."
      },
      {
        title: "Sida 50: Ekonomins aktörer",
        page: "50",
        track: "Båda",
        core: true,
        text: "Ekonomins aktörer\n\nEkonomins aktörer kallar vi alla dem som producerar varor och tjänster och ser till att Sverige är ett bra land att leva i. Först beskriver vi producenterna, aktörerna, uppdelade i fyra grupper. Sedan ser vi hur pengarna går runt mellan de här fyra aktörerna.\n\nDen offentliga sektorn\n\nVi som bor i Sverige äger mycket gemensamt. Kommunen äger de flesta skolor, äldreboenden, miljöstationer, räddningstjänsten, fotbollsplaner, gator, broar och mycket mer i din kommun. Regionen äger de flesta sjukhus, och bussar och annan kollektivtrafik inom länet eller regionen där du bor. Regeringen och riksdagen, staten, äger till exempel domstolar, våra universitet och högskolor, vårt militära försvar, Europavägar och riksvägar och mycket, mycket mer. Kommunerna, regionerna och staten kallas tillsammans den offentliga sektorn.\n\nDet som inte tillhör den offentliga sektorn, utan den privata sektorn är till exempel sådant som du, din familj och alla andra hushåll äger: leksaker, kläder, möbler, bilar, egna bostäder och så vidare. Till den privata sektorn hör också alla företag som finns, från kiosker och andra småföretag till storföretag som Volvo och Atlas Copco. Allt vad de som hör till den privata sektorn köper, måste de betala med egna pengar.",
        concepts: ["Offentlig sektor", "Privat sektor", "Stat", "Kommun"],
        mustKnow: ["Vem som äger skolor och sjukhus", "Skillnaden på privat och offentlig sektor"],
        summary: ["Vi äger skolor och vägar tillsammans i den offentliga sektorn", "Privata saker äger vi själva"],
        test: [{ q: "Vem äger domstolarna?", a: "Staten" }],
        reasoning: "Varför äger vi vissa saker gemensamt?",
        application: "Lista tre saker i ditt närområde som ägs av kommunen."
      },
      {
        title: "Sida 51: Skatter och Företag",
        page: "51",
        track: "Båda",
        core: true,
        text: "Skatter\n\nMen hur betalas då det som hör till den offentliga sektorn? Det kostar ju pengar att till exempel driva skolor och förskolor, att tömma soptunnor, att hålla vägar och gator snöfria. Svaret är skatter. Allt det som den offentliga sektorn sköter om betalas genom skatterna. It finns olika sorters skatt och det rör sig om mycket pengar:\n\n- Inkomstskatter. Det är den skatt som alla betalar på sin lön.\n- Mervärdesskatt. Men du som inte jobbar och inte har någon lön, betalar du ingen skatt? Jo, det gör du! När du köper en tröja för 100 kronor kostar tröjan egentligen bara 80 kronor. Affären betalar 20 kronor i mervärdesskatt (eller moms som man oftast säger) till Skatteverket.\n\nFöretagen\n\nI Sverige finns det hundratusentals företag. Företagen producerar, tillverkar, varor och tjänster som människorna (hushållen), konsumerar, använder.\n\nHEJ ALLA KUNDER\n- VI HAR KASSAREGISTER ENLIGT LAG\n- VI BETALAR SKATT\n- VI BETALAR MOMS\n- VI BETALAR ARBETSGIVARAVGIFTER\n- VI BETALAR LÖN ENLIG KOLLEKTIVAVTAL\nALLA GÖR INTE DET. TACK FÖR ATT NI STÖDJER SJYST KONKURRENS.",
        concepts: ["Moms", "Kollektivavtal", "Konkurrens"],
        mustKnow: ["Att alla betalar skatt via moms", "Vart skattepengarna går"],
        summary: ["Skatten går till välfärd som vård och skola", "Moms är skatt på varor"],
        test: [{ q: "Vad kallas skatten man betalar när man handlar?", a: "Moms" }],
        reasoning: "Vad händer om ett företag struntar i att betala skatt?",
        application: "Titta på ett kvitto. Hur mycket är moms?"
      },
      {
        title: "Sida 52: Banker och Ränta",
        page: "52",
        track: "Båda",
        core: true,
        text: "Hushållen\n\nAlla svenskar tillhör ett hushåll oavsett om man lever ensam eller i en familj. När hushållen köper företagens varor och tjänster får företagen in pengar. De anställda som arbetar och tillverkar varorna och tjänsterna får lön. Som du nyss har läst måste både företagen och hushållen betala skatt.\n\nBankerna\n\nRiksbanken är den enda som får göra mynt och trycka sedlar. De pengar bankerna har är pengar som företag och människor har lånat ut till banken. Om du har ett konto i en bank och sätter in 50 kronor i månaden, lånar du ju faktiskt ut dina pengar till banken. Det är de här pengarna som banken sedan i sin tur lånar ut till den som vill låna pengar, till exempel för att köpa ett hus eller en ny bil.\n\nHur får bankerna då råd med att betala löner till de anställda eller bygga och underhålla sina lokaler? Svaret är räntan. Banken tjänar pengar på att den betalar ut lite mindre i ränta till dig som spar pengar på banken, än den får in av dem som lånar av banken.\n\nDet är Riksbanken som i slutändan bestämmer räntan i Sverige. Om din familj har några miljoner i lån på bostaden är det lätt att förstå att det spelar roll om räntan är 4% eller 7%. Även alla som bor i hyreshus och betalar hyra för bostaden påverkas av räntan. Hyresvärdarna har nämligen stora lån, och om räntan höjs, kommer troligen också hyrorna att höjas.",
        concepts: ["Inlåning", "Utlåning", "Riksbanken"],
        mustKnow: ["Vem som trycker sedlar", "Hur banken tjänar pengar"],
        summary: ["Banken är en mellanhand för pengar", "Du får ränta när du sparar"],
        test: [{ q: "Vem bestämmer räntan i Sverige?", a: "Riksbanken" }],
        reasoning: "Varför påverkas hyran av bankens ränta?",
        application: "Fråga dina föräldrar vilken bank de använder."
      },
      {
        title: "Sida 53: Det ekonomiska kretsloppet",
        page: "53",
        track: "Båda",
        core: true,
        text: "Inlåningsränta och utlåningsränta - ett exempel\n\nVi antar du har 1000 kronor på ditt konto. Den som lånar ut sina pengar till banken får ränta. Räntan är inte så hög, kanske bara 1%. Det betyder att dina tusen kronor vuxit med 10 kronor. Den som lånar pengar betalar ränta, en högre ränta, kanske 5%. Mellanskillnaden kallas räntegap.\n\nDet ekonomiska kretsloppet\n\nNu ska vi se hur pengarna går runt mellan bankerna, företagen, hushållen och den offentliga sektorn. Det kallas för det ekonomiska kretsloppet.\n\nPilarna till hushåll:\n- från företag: lön.\n- från den offentliga sektorn: välfärd (bidrag, sjukersättning) och lön.\n- från bankerna: lån och ränta.\n\nPilarna från hushåll:\n- till företag: betalning för varor och tjänster.\n- till den offentliga sektorn: skatt.\n- till bankerna: insatta pengar och ränta på lån.",
        concepts: ["Kretslopp", "Räntegap", "Välfärd"],
        mustKnow: ["De fyra delarna i kretsloppet", "Vart pengarna går"],
        summary: ["Pengarna cirkulerar mellan hushåll, företag, banker och staten", "Alla delar hänger ihop"],
        test: [{ q: "Vad kallas bankens vinst?", a: "Räntegap" }],
        reasoning: "Vad händer i kretsloppet om ingen betalar skatt?",
        application: "Rita de fyra boxarna i kretsloppet."
      },
      {
        title: "Sida 54: Vem bestämmer priset?",
        page: "54",
        track: "Båda",
        core: true,
        text: "Vem bestämmer priset på en vara?\n\nHar du funderat över varför de allra första svenska jordgubbarna på försommaren är så dyra? Bara efter någon vecka är de mycket, mycket billigare. Vem har bestämt att det ska vara så?\n\nDet finns faktiskt en enkel förklaring. De allra första jordgubbarna är det ont om. Kanske kommer det bara 10 kartonger till affären. Ekonomerna säger att utbudet av jordgubbar är litet. De som odlar jordgubbar vet att de kan ta bra betalt och ändå få sålt.\n\nEfter någon vecka finns det mängder av jordgubbskartonger i affärerna. Utbudet har ökat. Vad händer då med priset? Kommer priset att vara detsamma? Nej, då skulle massor av jordgubbar bli osålda. Nu är kunder inte beredda att betala så mycket. Priset sjunker.\n\nMen priset kan ändras på annat sätt. Om efterfrågan på jordgubbar ökar påverkar det också priset. Genom utbud och efterfrågan bestäms priserna för nästan alla varor och tjänster.\n\nAKTIVITET - Det ekonomiska kretsloppet\nVad händer om många plötsligt blir arbetslösa?",
        concepts: ["Utbud", "Efterfrågan", "Pris"],
        mustKnow: ["Sambandet mellan utbud, efterfrågan och pris", "Varför priser ändras"],
        summary: ["Priset styrs av hur mycket som finns och hur många som vill köpa", "Lite jordgubbar = dyrt"],
        test: [{ q: "Vad händer med priset om utbudet ökar?", a: "Det sjunker" }],
        reasoning: "Varför är biobiljetter ibland billigare på eftermiddagen?",
        application: "Tänk på en vara. Är den billig eller dyr nu?"
      },
      {
        title: "Sida 55: Hållplats 2 Ekonomi",
        page: "55",
        track: "Båda",
        core: true,
        text: "SAMMANFATTNING\n\n• Pengarna i det ekonomiska kretsloppet går runt mellan hushållen, företagen, bankerna och den offentliga sektorn.\n• Kommunerna, regionerna och staten får in pengar genom inkomsskatt och mervärdesskatt (moms).\n• Hur hög eller hur låg räntan är påverkar allas ekonomi.\n• Utbud och efterfrågan bestämmer priset på varor och tjänster.\n\nVIKTIGA ORD\ninkomstskatt, mervärdesskatt (moms), arbetsgivaravgift, den offentliga sektorn, företag, hushåll, Riksbanken, det ekonomiska kretsloppet, ränta, räntegap, utbud, efterfrågan.",
        concepts: ["Sammanfattning", "Begrepp"],
        mustKnow: ["Alla sammanfattningspunkter", "De viktigaste orden"],
        summary: ["Här repeteras det ekonomiska kretsloppet och prissättning"],
        test: [{ q: "Hur får offentliga sektorn in pengar?", a: "Skatt och moms" }],
        reasoning: "Vilket ord i listan är viktigast för dig? Varför?",
        application: "Förklara för en vuxen vad efterfrågan betyder."
      }
    ]
  },
  {
    id: 3,
    title: "Lag och rätt – Regler och lagar",
    icon: "scale",
    subject: "Lag och rätt",
    sections: [
      {
        title: "Sida 56: Lag och rätt intro",
        page: "56",
        track: "Båda",
        core: true,
        text: "Lag och rätt\n\nI de allra äldsta kulturerna avgjorde kungen tvister mellan människor. Så småningom skrevs kungarnas beslut ned och de blev samhällets lagar. De som bröt mot lagarna blev straffade, och så är det än idag. En lag måste man följa för att inte riskera att bli straffad.\n\nMen det finns också regler som styr vad man bör göra och inte bör göra. Vad som är rätt och fel har människor funderat över i alla tider.\n\nLäs om\n- hur lagar och regler förändras över tid.\n- vilka skyldigheter och rättigheter allemansrätten ger.\n- polisens, åklagarens och domstolens uppgifter.\n- hur de som bryter mot lagen straffas.\n- vad kriminalitet innebär för samhället.",
        concepts: ["Lag", "Regel", "Tvister"],
        mustKnow: ["Att lagar funnits sedan kungarnas tid", "Skillnaden på lag och regel"],
        summary: ["Lagar är nedskrivna regler som ger straff vid brott"],
        test: [{ q: "Vem avgjorde tvister förr i tiden?", a: "Kungen" }],
        reasoning: "Varför behövs det skrivna lagar istället för bara funderingar?",
        application: "Nämn en lag som du tycker är bra."
      },
      {
        title: "Sida 57: Regler och normer",
        page: "57",
        track: "Båda",
        core: true,
        text: "Regler och normer\n\nDen gyllene regeln är en oskriven regel. Ofta handlar oskrivna regler om hur man bör vara och bör bete sig mot varandra. De här oskrivna reglerna kallas ibland normer. Man spottar inte på golvet, man rapar inte eller hostar utan att hålla för munnen när man är bland folk, man säger \"tack\" när man får hjälp av någon annan, man säger \"hej då\" till kompisens mamma eller pappa när man går hem. Samhällets normer ändras. Numer är det ingen som röker inomhus. Inte heller slänger man glödlampor och batterier i soppåsen.\n\nDen som bryter mot en regel kan inte dömas av en domstol. Men man kanske ändå ska tänka till innan man bryter mot en regel för man vill väl inte verka ohyfsad eller göra folk ledsna.\n\nAndra regler kan se olika ut i olika hem. Det kan gälla om man får äta framför tv:n, att man ska lägga sig en viss tid på vardagkvällar eller att man turas om att gå ut med hunden.",
        concepts: ["Normer", "Gyllene regeln", "Oskrivna regler"],
        mustKnow: ["Vad en norm är", "Att man inte kan dömas för brott mot normer"],
        summary: ["Normer är beteenden vi förväntar oss av varandra"],
        test: [{ q: "Vad kallas oskrivna regler?", a: "Normer" }],
        reasoning: "Varför ändras normer i samhället?",
        application: "Skriv ner tre regler ni har hemma hos dig."
      },
      {
        title: "Sida 58: Lagar",
        page: "58",
        track: "Båda",
        core: true,
        text: "Lagar\n\nEtt demokratiskt land ska vara ett rättssamhälle. I ett rättssamhälle är alla lika inför lagen. Fattig eller rik, alla ska behandlas och dömas lika om brottet de begått är detsamma. Ett rättssamhälle innebär också att det ska vara tydligt vad som är ett brott, och vad som inte är ett brott. Om något inte uttryckligen är förbjudet så är det tillåtet. Det ska också vara tydligt vilket straff det kan bli om man begår ett brott. I lagboken används inte ordet straff utan ordet påföljd, men i dagligt tal används ofta ordet straff.\n\nDet är riksdagen som beslutar om alla lagar. Lagarna finns samlade i lagboken som med åren blivit en tjock bok, över 4 000 sidor. Lagboken är indelad i olika avsnitt som kallas balkar. Varje år ändras många lagar och nya lagar tillkommer. De som kan alla lagarna kallas jurister och de har läst juridik vid universitet. Tur är det, för en lag måste man följa. Man kan aldrig ursäkta sig med att man inte kände till lagen.",
        concepts: ["Rättssamhälle", "Påföljd", "Jurist", "Balkar"],
        mustKnow: ["Att alla är lika inför lagen", "Att riksdagen bestämmer lagar"],
        summary: ["Sverige är ett rättssamhälle där alla är lika inför lagen"],
        test: [{ q: "Vem beslutar om lagarna i Sverige?", a: "Riksdagen" }],
        reasoning: "Vad händer om en lag inte är tydlig?",
        application: "Försök gissa hur många sidor lagboken har."
      }
    ]
  },
  {
    id: 4,
    title: "Lag och rätt – Lagar i praktiken",
    icon: "gavel",
    subject: "Lag och rätt",
    sections: [
      {
        title: "Sida 59: Nya lagar",
        page: "59",
        track: "Båda",
        core: true,
        text: "Nya lagar\n\nNär Sverige fick en ny skollag 2011 bestämdes det att skolmaten inte bara skulle vara gratis, utan från och med nu också vara näringsriktig. Den här lagändringen gjorde att alla som hade ansvar för skolmåltiderna fick fundera över om de skulle behöva ändra på något.\n\nEn ny lag som berör oss alla började gälla våren 2020, skatt på plastpåsar. I propositionen föreslogs att det införs en punktskatt på plastbärkassar. Skatten omfattar inte plastbärkassar avsedda för varaktigt bruk. Skatten tas ut med tre kronor per plastbärkasse.\n\nDet här läromedlet beskriver flera lagar. I kapitlet Jobben och arbetsmarknaden nämns bland annat arbetsmiljölagen. En ny lag började gälla 2018, klimatlagen. Den säger bland annat att utsläppen från inrikes transporter ska minska rejält fram till 2030.\n\nIbland krävs det nya lagar. Vad som är brottsligt har förändrats under århundradena. Föräldrar och lärare hade förr rätt att slå barn (aga barn), vilket idag är brottsligt. Från 2021 bryter en förare mot lagen om man spelar maxvolym sent på kvällen.",
        concepts: ["Proposition", "Punktskatt", "Aga", "Klimatlagen"],
        mustKnow: ["Att lagar ändras över tid", "Exempel på nya lagar"],
        summary: ["Lagar skapas när samhället förändras", "Aga förbjöds för att skydda barn"],
        test: [{ q: "Vad kostade en plastpåse i skatt enligt lagen?", a: "3 kronor" }],
        reasoning: "Varför behövs det lagar om miljön och klimatet?",
        application: "Kolla vad en plastpåse kostar i din mataffär idag."
      },
      {
        title: "Sida 60: Allemansrätten",
        page: "60",
        track: "Båda",
        core: true,
        text: "Allemansrätten\n\nSverige är fantastiskt! Det tycker de allra flesta. Vi har ju alla rätt att gå och cykla i skog och mark och plocka blommor, bär och svamp. Det kallas allemansrätten och den finns inskriven i regeringsformen: \"Alla ska ha tillgång till naturen enligt allemansrätten.\"\n\nI de flesta länder finns ingen allemansrätt. Man har inte rätt att vara i skog eller annan mark som ägs av någon annan. I USA till exempel kan markägaren förbjuda att folk badar i en insjö även om den ligger många kilometer från närmaste hus.\n\nInte störa och inte förstöra\n\nVi måste vårda och vara rädda om naturen! Inte störa och inte förstöra är huvudregeln i allemansrätten.\n\nDu får\n- gå på annans mark som inte är tomtmark.\n- tälta någon natt på annans mark.\n- gå över beteshagar om du stänger alla grindar.\n- bada och åka båt.\n- plocka vilda bär, svamp och ej fridlysta växter.\n- fiska och meta i Sveriges fem största sjöar.\n\nDu får inte\n- gå över en nysådd åker eller tomt.\n- fiska utan fiskekort i småsjöar.\n- vara oförsiktig med elden.\n- tälta på en tomt.",
        concepts: ["Allemansrätten", "Fridlyst", "Tomtmark"],
        mustKnow: ["Huvudregeln: Inte störa, inte förstöra", "Vad man får och inte får göra"],
        summary: ["Vi får vara i naturen med ansvar", "Allemansrätten står i grundlagen"],
        test: [{ q: "Vad är allemansrättens huvudregel?", a: "Inte störa och inte förstöra" }],
        reasoning: "Varför är allemansrätten viktig för oss som bor i Sverige?",
        application: "Rita tre saker du får göra i skogen."
      },
      {
        title: "Sida 61: Hållplats 1 Lag och rätt",
        page: "61",
        track: "Båda",
        core: true,
        text: "SAMMANFATTNING\n\n• Du kan inte dömas i domstol om du bryter mot en regel.\n• I ett rättssamhälle ska alla brott och straff vara inskrivna i lagboken.\n• \"Inte störa, inte förstöra\" är allemansrättens huvudregel.\n• Bryter du mot en lag kan du dömas i domstol.\n• Riksdagen beslutar om vilka lagar som gäller.\n\nVIKTIGA ORD\noskrivna regler, normer, lagar, allemansrätten, påföljd, skollagen, klimatlagen, förargelseväckande beteende, rättssamhälle, juridik, straff, proposition.",
        concepts: ["Rättssamhälle", "Juridik", "Sammanfattning"],
        mustKnow: ["Alla sammanfattningspunkter", "Alla viktiga ord"],
        summary: ["Här repeteras vad en lag är och hur de skiljer sig från regler"],
        test: [{ q: "Kan man dömas för att bryta en regel?", a: "Nej" }],
        reasoning: "Varför är det viktigt att alla lagar finns skrivna i en bok?",
        application: "Förklara ordet 'normer' för en kompis."
      },
      {
        title: "Sida 62: Polisen, åklagaren, domstolen",
        page: "62",
        track: "Båda",
        core: true,
        text: "Polisen, åklagarens och domstolens uppgifter är centrala i rättssamhället. När ett brott har begåtts är det polisens sak att undersöka vad som hänt. De förhör vittnen och misstänkta. Om polisen tror att de har hittat den skyldige tar en åklagare vid. Åklagaren går igenom polisens utredning och beslutar om det ska bli rättegång. I domstolen avgörs sedan om den misstänkte är skyldig. En domare och nämndemän lyssnar på bevis och bestämmer påföljd, alltså straff. Det kan vara böter eller fängelse. För unga lagöverträdare finns särskilda regler för att hjälpa dem tillbaka till ett liv utan brott.",
        concepts: ["Gripa", "Anhålla", "Häkta", "Åklagare"],
        mustKnow: ["Tidsgränsen för anhållande (3 dygn)", "Skillnaden på att vara gripen och häktad"],
        summary: ["Processen går via polis till åklagare och domstol"],
        test: [{ q: "Vem beslutar om en person ska anhållas?", a: "Åklagaren" }],
        reasoning: "Varför kan man inte bara låsa in den skyldige direkt?",
        application: "Gör ett flödesschema över vägen från gripande till åtal."
      },
      {
        title: "Sida 63: Domstolen dömer",
        page: "63",
        track: "Båda",
        core: true,
        text: "Domstolen dömer\n\nVid rättegången berättar åklagaren för domarna allt som talar för att den åtalade är skyldig. Den åtalades försvarsadvokat däremot berättar allt som talar för att den åtalade är oskyldig. Domstolen kommer sedan att bestämma om den åtalade är skyldig eller oskyldig. Domstolen ska döma, fälla, en person bara om domstolen är säker på att inte någon annan kunde ha begått brottet. Om domstolen inte är säker på sin sak bör den \"hellre fria än fälla\". Det betyder att den ska frikänna, släppa den åtalade fri. Det betyder att det finns en och annan skyldig som blir frikänd för att det inte finns tillräckligt med bevis. Däremot ska ingen oskyldig person dömas.\n\nVilken påföljd ska den skyldige få?\n\nOm domstolen kommer fram till att den åtalade är skyldig, ska också brottet fastställas. Den här bråkande personen på stan, vilket brott har han gjort sig skyldig till: olaga hot? misshandel, lindrig misshandel eller grov misshandel? Därefter ska domstolen bestämma straffet, påföljden.\n\nPåföljden är inte exakt densamma för alla som begår samma brott. Domstolen tar hänsyn till om det finns någon förmildrande omständighet som kan göra att domstolen dömer ett lindrigt straff. En som begår brott första gången bedöms troligen lindrigare än den som har dömts flera gånger tidigare. Eller finns det något försvårande som gör att domstolen dömer ett hårdare straff?",
        concepts: ["Fria än fälla", "Frikänna", "Förmildrande omständigheter"],
        mustKnow: ["Att man är oskyldig tills motsatsen bevisats", "Att straffet beror på omständigheter"],
        summary: ["Domstolen väger bevis och dömer eller friar"],
        test: [{ q: "Vad betyder det att domstolen 'fäller' någon?", a: "Att man dömer personen som skyldig" }],
        reasoning: "Är det bra eller dåligt att man får kortare straff om det är första gången?",
        application: "Ge exempel på en försvårande omständighet."
      },
      {
        title: "Sida 64: Brott på internet",
        page: "64",
        track: "Båda",
        core: true,
        text: "Så här kan det se ut vid en rättegång. Vid det långa bordet sitter juristdomaren, notarien och de tre nämndemännen. Till höger på bilden sitter den åtalade och hans försvarsadvokat. Till vänster på bilden sitter åklagaren och brottsoffret (den målsägande). Vid det lilla bordet sitter ett vittne.\n\nStraffet för snatteri (kallas \"ringa stöld\" i lagboken) till exempel varierar från böter till högst 6 månaders fängelse. Domstolen dömer inte den som snattat en och två gånger till fängelse, men den som snattat många gånger kan få fängelse. Dessutom tar domstolen hänsyn till brottslingens ålder, åtminstone när det gäller mindre allvarliga brott.\n\nBrott på internet\n\nIdag har många människor tillgång till internet. Internet ger oss möjlighet att leta efter fakta, söka information, hålla kontakt med människor med mera. Det innebär också att vi har ansvar för vad vi skriver och vilka bilder vi laddar upp. It kan till exempel vara brottsligt att sprida rykten eller att förolämpa någon. Detta gäller både när vi pratar och när vi skriver till exempel på internet. Man måste också tänka sig för vilka bilder av andra man lägger ut. Tänk så här: \"Vilka bilder på mig skulle jag vilja spreds på sociala medier?\" Man får inte heller säga att man är någon annan för att lura folk. Var uppmärksam när du chattar på internet och tänk dig för.",
        concepts: ["Målsägande", "Förtal", "Internetansvar"],
        mustKnow: ["Att lagar även gäller på internet", "Vem som sitter i rättegångssalen"],
        summary: ["Nätet är inte laglöst område", "Vissa rykten kan vara förtal"],
        test: [{ q: "Vad kallas brottsoffret i rättegången?", a: "Målsägande" }],
        reasoning: "Varför är nätmobbning lika allvarligt som mobbning på skolgården?",
        application: "Gör en checklista för vad man får lägga upp på nätet."
      },
      {
        title: "Sida 65: Aktivitet Värdera brott",
        page: "65",
        track: "Båda",
        core: true,
        text: "AKTIVITET - Värdera brott\n\nNu ska du få fundera vilka brott som är allvarliga och vilka som är mindre allvarliga.\n\nTabell A:\n- utpressning\n- grov misshandel\n- ringa stöld (snatteri)\n\nTabell B:\n- gromning (kontakta barn i sexuellt syfte via chatt)\n- förtal (sprida rykten)\n- skadegörelse (förstöra något man inte äger)\n\nTabell C:\n- åverkan (lindrig skadegörelse)\n- sexuellt ofredande (blottning eller beröra barn under 15)\n- olaga hot (hota nån så den blir allvarligt rädd)\n\n1. Markera med 1 det brott du tycker ska ha hårdaste straffet, 2 för mellan och 3 för lägsta.\n2. Jämför med en kompis. Tycker ni lika?\n3. Håller du med domstolarnas värdering?",
        concepts: ["Värdering", "Gromning", "Olaga hot"],
        mustKnow: ["Att olika brott ger olika hårda straff", "Vad orden i tabellerna betyder"],
        summary: ["Här får eleverna öva på att rangordna brott"],
        test: [{ q: "Vad är åverkan?", a: "Lindrig skadegörelse" }],
        reasoning: "Varför straffas misshandel hårdare än stöld av en godisbit?",
        application: "Rangordna Tabell A."
      },
      {
        title: "Sida 66: Hållplats 2 Lag och rätt",
        page: "66",
        track: "Båda",
        core: true,
        text: "SAMMANFATTNING\n\n• När en person grips av polisen, ska en åklagare omedelbart avgöra om hen ska anhållas eller släppas fri.\n• Åklagaren måste inom tre dygn besluta om en anhållen person ska släppas fri eller begäras häktad.\n• Åklagaren ska väcka åtal mot en åtalad om åklagaren tror att den åtalade blir dömd.\n• Om domstolen inte är säker på att den åtalade är skyldig bör den fria.\n• Domstolen tar hänsyn till förmildrande eller försvårande omständigheter när domstolen utdömer straffet.\n\nVIKTIGA ORD\nåklagare, gripa, anhålla, häkta, snatteri, väcka åtal, rättegång, skadegörelse, åverkan, misshandel, utpressning, förtal.",
        concepts: ["Åtal", "Vittne", "Repetition"],
        mustKnow: ["Alla steg i processen", "De viktigaste juridiska orden"],
        summary: ["Här sammanfattas polisens och åklagarens roller"],
        test: [{ q: "Hur länge får man vara anhållen?", a: "Max tre dygn" }],
        reasoning: "Vilken är den viktigaste uppgiften för en åklagare?",
        application: "Hitta på en egen förklaring till ordet 'häkta'."
      },
      {
        title: "Sida 67: Ungdomar och brott",
        page: "67",
        track: "Båda",
        core: true,
        text: "Ungdomar och brott\n\nOm en 12-åring bryter mot lagen är det lika brottsligt som om en vuxen gör det. Men den som är under 15 år är inte straffmyndig. Att vara straffmyndig betyder att man är gammal nog att bli dömd för de brott som man begår. En 12-åring som begår ett brott kan alltså inte dömas. En 15-åring däremot som är misstänkt för att ha begått brott kan åtalas av åklagare och ställas inför domstol.\n\nMen vad händer när en 12-åring åker dit för ringa stöld (snatteri)? Vi kallar snattaren för Mira.\n\nICA-handlaren Marcus berättar: \"Jag ringer alltid polisen när någon snattar, även om det är ett barn. Det blir bäst så, även för snattaren. Alla ärliga kunder får ju betala för vad några stycken stjäl.\"\n\nVad händer sedan? Polisen Jan berättar: \"När vi ser att det är en ung snattare ringer vi alltid vårdnadshavaren. Antingen hämtar en förälder barnet eller kör vi hem barnet. Sedan skickar vi polisanmälan till socialtjänsten.\"\n\nSocialsekreteraren Madeleine berättar: \"Ofta föreslår vi medling. Barnet följer med till affären, ber om förlåtelse och skakar hand med handlaren. Ofta är det sista gången det här barnet snattar.\"",
        concepts: ["Straffmyndig", "Vårdnadshavare", "Medling", "Socialtjänsten"],
        mustKnow: ["Att gränsen för att dömas är 15 år", "Vad medling innebär"],
        summary: ["Barn under 15 döms ej i rätten utan hanteras av socialtjänsten"],
        test: [{ q: "Vilken ålder måste man ha för att vara straffmyndig?", a: "15 år" }],
        reasoning: "Varför dömer vi inte barn under 15 i domstol?",
        application: "Diskutera: Varför säger handlaren att ärliga kunder får betala för stöld?"
      },
      {
        title: "Sida 68: Socialnämndens ansvar",
        page: "68",
        track: "Båda",
        core: true,
        text: "Socialnämnden har ansvaret för unga brottslingar\n\nEtt fåtal barn och ungdomar begår många brott eller begår allvarliga brott. Det kan vara ett gäng tjejer på 12-13 år som stjäl plånböcker från äldre personer. Det kan vara några killar på 12-14 år som driver omkring på stan och rånar ensamma killar eller tjejer.\n\nSocialtjänstlagen bestämmer att om föräldrarna inte kan ta hand om sitt barn på ett bra sätt, kan socialnämnden besluta att familjen ska få en stödperson som träffar barnet och familjen, kanske flera gånger i veckan. Stödpersonen försöker hjälpa till och samtidigt se till att barnet inte fortsätter att begå brott. Socialnämnden består av politiker i kommunen som bestämmer vad socialsekreterarna ska göra. Allt som bestäms ska vara för barnets bästa.\n\nIbland kommer socialnämnden fram till att det är föräldrarna som är huvudproblemet, inte barnet. Då kan socialnämnden bestämma att barnet inte längre får bo hemma. Istället ska barnet bo i ett familjehem. Ofta har de här barnen begått grova brott som rån. Antalet barn som rånar andra barn har mer än fördubblats under senare år.",
        concepts: ["Socialnämnd", "Stödperson", "Barnets bästa", "Familjehem"],
        mustKnow: ["Att socialnämnden beslutar om stödåtgärder", "Begreppet 'Barnets bästa'"],
        summary: ["Socialtjänsten sätter in stöd eller ordnar familjehem vid grova problem"],
        test: [{ q: "Vem består socialnämnden av?", a: "Politiker i kommunen" }],
        reasoning: "Varför är det viktigt att politiker och inte bara poliser bestämmer om barn?",
        application: "Förklara vad en stödperson gör."
      },
      {
        title: "Sida 69: Skadeståndsskyldig",
        page: "69",
        track: "Båda",
        core: true,
        text: "Ungdomar som fortsätter med allvarliga brott kan hamna på ett slutet behandlingshem, där de ska få omvårdnad och stöd medan de går i skolan. Att behandlingshemmet är slutet innebär att ungdomarna är inlåsta och inte kan röra sig fritt.\n\nSkadeståndsskyldig, men inte straffmyndig\n\nFrida är 13 år. Under en skoldag tänder hon eld på en papperskorg på en toa. Elden tar sig, larmet går, skolan utryms. Delar av skolbyggnaden brinner upp. Polisen utreder förberedelse till mordbrand. Frida grips och erkänner: \"Jag ville bara sabba lite\".\n\nVad händer? Frida är inte straffmyndig så hon kan inte dömas. Men försäkringsbolaget skickar ett krav på skadestånd till Frida. Det kan vara miljoner. Barn under 15 år är inte straffmyndiga men skadeståndsansvaret gäller även för barn långt under 15 år. Skulden växer hela tiden eftersom försäkringsbolaget får ränta på skulden. När Frida börjar tjäna pengar som vuxen dras pengar från lönen varje månad. I bästa fall är hon skuldfri i 30-årsåldern.\n\nFörsäkringsbolagen lägger inte ned processen bara för att barnet inte har pengar. Det är sådana processer i Sverige varje vecka.",
        concepts: ["Slutet behandlingshem", "Skadestånd", "Mordbrand"],
        mustKnow: ["Att man kan bli skadeståndsskyldig innan man är 15", "Hur en skuld påverkar framtiden"],
        summary: ["Även om man inte får fängelse kan man tvingas betala miljoner"],
        test: [{ q: "Från vilken ålder gäller skadeståndsansvar?", a: "Från låg ålder, långt under 15 år" }],
        reasoning: "Är det rättvist att en 13-åring får skulder för hela sitt liv?",
        application: "Räkna ut: Om Frida betalar 2000 kr i månaden, hur lång tid tar det att betala 1 miljon?"
      },
      {
        title: "Sida 70: Konsekvenser av kriminalitet",
        page: "70",
        track: "Båda",
        core: true,
        text: "Konsekvenser av kriminalitet\n\nför den enskilde\nHur påverkar brottslighet Miras och Fridas liv? Om det var sista gången Mira snattade blir det inga konsekvenser. Hennes namn raderas ur register efter en tid. Frida däremot har skadeståndet som förföljer henne. För de som begår grövre brott är det komplicerat. De kan knappast ta körkort de närmaste åren. Många arbetsgivare kollar belastningsregistret och då kan det vara svårt att få jobb.\n\noch för samhället\nKriminaliteten är ett jätteproblem som kostar enorma pengar. Polisens uppgift är också att förhindra att brott sker. Det är därför poliser bevakar fotbollsmatcher eller gör nykterhetskontroller.\n\nNarkotika kostar inte bara pengar utan också mycket personligt lidande. Narkomaner begår brott för att skaffa narkotika. Risken är stor att de begår ytterligare brott när de är påverkade. Svensk polis samarbetar med Europol för att stoppa knarket.",
        concepts: ["Belastningsregister", "Kriminalitet", "Europol"],
        mustKnow: ["Vad belastningsregistret är", "Hur brott påverkar chanserna till jobb"],
        summary: ["Brott ger konsekvenser för både personen och hela samhället"],
        test: [{ q: "Vad kollar arbetsgivare för att se om man är dömd?", a: "Belastningsregistret" }],
        reasoning: "Varför vill en arbetsgivare veta om man begått brott förut?",
        application: "Ge exempel på vad polisen gör för att förhindra brott."
      },
      {
        title: "Sida 71: Otrygghet och fängelser",
        page: "71",
        track: "Båda",
        core: true,
        text: "Kriminaliteten skapar otrygghet. Många vågar inte gå ut på kvällarna av rädsla för rån eller misshandel. Polisens resurser räcker inte till för att vara överallt.\n\nFängelser\nI Åkersberga ligger Österåkeranstalten, en klass 2-anstalt. Där förvaras drygt 80 fångar. Kumla och sex andra fängelser har högsta säkerheten (klass 1). Klass 3-anstalter är öppna anstalter där de intagna har relativt stor frihet.\n\nOrganiserad brottslighet kallas sådan verksamhet som bedrivs av ligor och som tjänar pengar på t.ex. narkotikasmuggling och människohandel. De här brottslingarna är proffs och vet exakt hur de ska komma undan polisen.",
        concepts: ["Organiserad brottslighet", "Säkerhetsklass", "Anstalt"],
        mustKnow: ["Skillnaden på olika typer av fängelser", "Vad organiserad brottslighet innebär"],
        summary: ["Det finns olika säkerhetsklasser på fängelser i Sverige"],
        test: [{ q: "Vilken klass har fängelser med högst säkerhet?", a: "Klass 1" }],
        reasoning: "Varför är organiserad brottslighet svårare för polisen att stoppa?",
        application: "Ta reda på var närmaste fängelse ligger."
      },
      {
        title: "Sida 72: Aktivitet Unga och grova brott",
        page: "72",
        track: "Båda",
        core: true,
        text: "AKTIVITET - Vad gör man med unga som begår grova brott?\n\nHur bör barn under 15 år som rånar andra behandlas? Här är två åsikter.\n\nModeraterna:\n- Begränsa möjligheten att vårda i hemmet.\n- Häkta fler unga vid allvarliga brott.\n- Fler särskilda ungdomshäkten där de kan studera.\n\nVänsterpartiet:\n- Starkare insatser från socialtjänst och skola.\n- Rikta resurser tidigt mot de som är i riskzonen.\n- Inlåsning stärker bara ett kriminellt beteende.\n\n1. Vilket parti vill ha hårdare straff snabbare?\n2. Vilket parti betonar förebyggande åtgärder?\n3. Hur resonerar Vänsterpartiet om riskerna med inlåsning?\n4. Vilken metod tror du ger mest effekt?",
        concepts: ["Politisk debatt", "Häktning", "Förebyggande"],
        mustKnow: ["Att partier har olika lösningar på brottslighet", "Argument för och emot inlåsning"],
        summary: ["Här får eleverna öva på att ta ställning i en politisk debatt om ungdomsbrott"],
        test: [{ q: "Vad kallas åtgärder som ska stoppa brott innan de sker?", a: "Förebyggande åtgärder" }],
        reasoning: "Är det bättre att straffa eller att hjälpa en ung brottsling?",
        application: "Välj ett argument från Moderaterna och ett från Vänsterpartiet."
      },
      {
        title: "Sida 73: Hållplats 3 Lag och rätt",
        page: "73",
        track: "Båda",
        core: true,
        text: "SAMMANFATTNING\n\n• Socialtjänsten tar hand om minderåriga som har har snattat eller begått annat brott.\n• Du är straffmyndig när du fyllt 15 år. Men även barn och ungdomar under 15 år är skadeståndsansvariga.\n• Den organiserade brottsligheten är ett stort samhällsproblem.\n• Brottsligheten kostar samhället mycket pengar men också mycket personligt lidande.\n\nVIKTIGA ORD\nstraffmyndig, medling, socialtjänstlagen, belastningsregistret, skadeståndsansvar, förberedelse till mordbrand, organiserad brottslighet, stödperson, barnets bästa, familjehem, slutet behandlingshem.",
        concepts: ["Skadeståndsansvar", "Slutet behandlingshem", "Sammanfattning"],
        mustKnow: ["Alla sammanfattningens punkter", "Alla ord i listan"],
        summary: ["Här repeteras ungas ansvar och socialtjänstens roll"],
        test: [{ q: "Vad kallas stöld i lagboken?", a: "Ringa stöld (vid snatteri)" }],
        reasoning: "Vilken är den viktigaste saken du lärt dig i detta block?",
        application: "Gör ett korsord med 5 av orden i listan."
      }
    ]
  },
  {
    id: 5,
    title: "Demokrati – Val och partier",
    icon: "users",
    subject: "Demokrati",
    sections: [
      {
        title: "Sida 74: Demokrati och Diktatur",
        page: "74",
        track: "Båda",
        core: true,
        text: "Demokrati och Diktatur\n\nDina föräldrar är inte nöjda med hur skolan där du går fungerar. Därför skriver de en kritisk insändare. Nu kan det hända två saker beroende på om du bor i en demokrati eller i en diktatur:\n\n1. Skolpolitikerna svarar på insändaren och berättar hur de tycker att det är i skolan och vad som skulle kunna förbättras. Rektorn bjuder in dina föräldrar för ett samtal. Du får gärna vara med om du vill.\n2. Politikerna i din kommun bestämmer att dina föräldrar ska avskedas från jobbet. Din äldre bror får inte fortsätta studera på universitetet. Du själv mobbas av rektorn och lärarna på skolan.\n\nVilket alternativ är en diktatur? Och vilket är en demokrati?",
        concepts: ["Demokrati", "Diktatur", "Insändare"],
        mustKnow: ["Skillnaden mellan demokrati och diktatur", "Vad kapitlet handlar om"],
        summary: ["I en demokrati får man tycka vad man vill", "I en diktatur blir man straffad för kritik"],
        test: [{ q: "Vad händer med föräldrarna i exemplet med diktatur?", a: "De avskedas från jobbet" }],
        reasoning: "Varför är det viktigt att få kritisera skolan i en insändare?",
        application: "Tänk ut en sak du vill ändra på i din skola."
      },
      {
        title: "Sida 75: Vad är demokrati?",
        page: "75",
        track: "Båda",
        core: true,
        text: "Vad är demokrati?\n\nVi börjar med att förklara vad demokrati är. Demokratiska länder har det här gemensamt:\n\n- Allmän och lika rösträtt: Alla människor i landet över en viss ålder får rösta, och alla har en röst. Alla människor har alltså lika värde.\n- Yttrandefrihet: Alla har rätt att säga och skriva vad man vill. Man kan fritt uttrycka sina åsikter. Men även i en demokrati kan det vara olagligt att skriva och säga vissa saker.\n- Hänsyn till minoriteterna: Majoriteten måste tänka på minoriteterna och ta hänsyn till dem.\n\nOrdet demokrati kommer från grekiskan och betyder folkmakt, det är folket som ska bestämma, inte kungen eller någon annan. Men demokrati handlar inte bara om politik. Demokratin gäller också för dig och dina kompisar i skolan.",
        concepts: ["Rösträtt", "Yttrandefrihet", "Minoritet", "Folkmakt"],
        mustKnow: ["Betydelsen av ordet demokrati", "Kraven för ett demokratiskt land"],
        summary: ["Demokrati betyder att folket har makten", "Alla röster är värda lika mycket"],
        test: [{ q: "Från vilket land/språk kommer ordet demokrati?", a: "Grekiskan" }],
        reasoning: "Varför måste majoriteten ta hänsyn till minoriteten?",
        application: "Nämn en sak du har rätt att säga i Sverige."
      },
      {
        title: "Sida 76: Demokrati i skolan och klassen",
        page: "76",
        track: "Båda",
        core: true,
        text: "Demokratin började i Athen för cirka 2 500 år sedan. Templet Parthenon byggdes på 400-talet före Kristus efter beslut av invånarna i Athen.\n\nDemokrati i skolan och i klassen\n\nKlass 6B har klassråd och ska diskutera och besluta om klassresan på våren. Om det finns tid ska också hopprutorna på skolgården diskuteras. En dagordning är en lista på frågor som ska diskuteras och beslutas på mötet.\n\nFörst ska man välja en ordförande för mötet. Hen ska leda mötet, det vill säga bestämma vem som får prata. En bra ordförande försöker få alla att säga något.\n\nDärefter väljer man en sekreterare och en eller två justerare. Sekreterarens uppgift är att skriva protokoll. Justeraren ska kontrollera att det som står i protokollet stämmer med det som beslutades. Protokollet är alltså en källa till vad som hände. När alla fört fram sina förslag, är det dags att rösta. Det förslag som har fått majoritet, har fått flest röster, vinner - alltså majoritetsprincipen gäller.",
        concepts: ["Dagordning", "Ordförande", "Sekreterare", "Protokoll", "Justerare"],
        mustKnow: ["Vad en dagordning är", "Rollerna på ett möte", "Majoritetsprincipen"],
        summary: ["Klassrådet är demokrati i praktiken", "Man väljer roller som ordförande och sekreterare"],
        test: [{ q: "Vad gör en sekreterare?", a: "Skriver protokoll" }],
        reasoning: "Varför är det bra att ha en justerare på mötet?",
        application: "Vem skulle du vilja ha som ordförande i din klass?"
      },
      {
        title: "Sida 78: Hållplats 1 Demokrati",
        page: "78",
        track: "Båda",
        core: true,
        text: "SAMMANFATTNING\n\nDemokrati förutsätter\n- allmän och lika rösträtt (alla får rösta och alla har en röst)\n- yttrandefrihet (att alla får föra fram sina åsikter)\n- och att de styrande tar hänsyn till minoriteter.\n\nDemokrati fungerar också i klassrummet i skolan.\n\nVIKTIGA ORD\ndemokrati, allmän och lika rösträtt, yttrandefrihet, majoritetsprincipen, hänsyn till minoriteter, dagordning, protokoll, sekreterare, justerare, ordförande, rösta.\n\nVal och folkomröstningar\nIdag är det folket som har makten. Folket visar sin vilja genom att rösta, gå till val och välja mellan olika politiska partier. Vart fjärde år är det val till riksdagen. Valdagen är alltid andra söndagen i september. Man måste vara 18 år och svensk medborgare för att få rösta i riksdagsvalet.",
        concepts: ["Rösträtt", "Vart fjärde år", "Sammanfattning"],
        mustKnow: ["Sammanfattningens punkter", "Alla viktiga ord"],
        summary: ["Här repeteras grunderna i demokrati och valsystemet"],
        test: [{ q: "När är det val i Sverige?", a: "Andra söndagen i september vart fjärde år" }],
        reasoning: "Varför är lika rösträtt så viktigt för demokratin?",
        application: "Välj ett ord från listan och förklara det."
      },
      {
        title: "Sida 79: Valrörelsen och representation",
        page: "79",
        track: "Båda",
        core: true,
        text: "De politiska debatterna månaderna före valet kallas valrörelsen. Alla politiska partier försöker få så många väljare som möjligt att rösta på deras parti. På valdagen står ofta de politiska partiernas medlemmar utanför vallokalen och delar ut valsedlar. I vallokalen finns det gröna skärmar. Man går bakom en skärm och lägger en valsedel i ett kuvert och klistrar igen det. Ingen får veta på vilket parti man har röstat: valhemligheten är viktig.\n\nDe flesta länder gör som vi i Sverige: folket väljer politiker som sedan får besluta. Politikerna representerar sina väljare. Därför kallas den formen för representativ demokrati.\n\nMen ibland tillämpar vi i Sverige en annan form av demokrati, genom folkomröstning. Folkomröstningar är bara rådgivande, det vill säga politikerna behöver inte följa resultatet. De kan mycket väl besluta något annat. Metoden kallas direktdemokrati. I Schweiz är direktdemokratin mycket vanlig.",
        concepts: ["Valrörelsen", "Valhemlighet", "Representativ demokrati", "Direktdemokrati"],
        mustKnow: ["Vad representativ demokrati betyder", "Skillnaden på direkt och representativ", "Vikten av valhemlighet"],
        summary: ["Vi väljer politiker som bestämmer åt oss", "Rösten är alltid hemlig"],
        test: [{ q: "Vad kallas demokrati med folkomröstningar?", a: "Direktdemokrati" }],
        reasoning: "Varför är folkomröstningar bara rådgivande i Sverige?",
        application: "Hitta en bild på en valstuga."
      },
      {
        title: "Sida 80: Partierna i riksdagen",
        page: "80",
        track: "Båda",
        core: true,
        text: "Partierna i riksdagen\n\nI Sveriges riksdag sitter för närvarande åtta partier: Socialdemokraterna, Vänsterpartiet, Miljöpartiet, Moderaterna, Liberalerna, Centerpartiet, Kristdemokraterna och Sverigedemokraterna.\n\nSocialdemokraterna och Vänsterpartiet kallas ibland socialistiska partier. De vill att skolor, äldreboenden och vårdcentraler ägs och drivs av kommunerna och regionerna. De vill ha en stark offentlig sektor. De kallas ofta de röd-gröna när de samarbetar.\n\nModeraterna, Kristdemokraterna, Sverigedemokraterna kallas ofta ett konservativt block som också Liberalerna vill ansluta sig till. De menar att det är bra med privata skolor och äldreboenden och vill begränsa invandringen mer än de röd-gröna.\n\nRiksdagen består av 349 ledamöter. För att komma in i riksdagen måste ett politiskt parti få minst 4 procent av alla röster. Den här fyra-procents-spärren har riksdagen bestämt för att det inte ska bli för många småpartier i riksdagen.",
        concepts: ["Socialistisk", "Konservativ", "Ledamot", "Fyra-procents-spärren"],
        mustKnow: ["Hur många ledamöter riksdagen har", "Vad fyra-procents-spärren är"],
        summary: ["Det finns åtta partier i riksdagen", "Partierna delas ofta in i block"],
        test: [{ q: "Hur många ledamöter finns i riksdagen?", a: "349 stycken" }],
        reasoning: "Varför vill vissa partier ha mer privata alternativ än andra?",
        application: "Lista namnen på de åtta partierna."
      },
      {
        title: "Sida 81: Vad är diktatur?",
        page: "81",
        track: "Båda",
        core: true,
        text: "Vad är diktatur?\n\nI en diktatur är det ett parti som har makten och som till och med tar till våld för att behålla makten. De som tycker annorlunda än det styrande partiet förföljs, förlorar jobbet, sätts i fängelse eller blir till och med mördade. Många diktaturer har politiska val med allmän rösträtt. Men när det bara finns ett parti att rösta på är det självklart att det partiet vinner. Journalister hotas eller mördas.\n\nDe flesta länder som är diktaturer finns i Asien och Afrika. Eritrea, Iran och Nordkorea är några av de länder som brukar anges som de grymmaste diktaturerna i världen. En del diktaturer är \"snällare\" och kallas auktoritära länder.\n\nSå här fungerar diktaturen Nordkorea\nNordkoreas diktator heter Kim Jong-Un. När det är val måste alla över 17 år rösta. Den som inte röstar blir misstänkt för att inte stödja Kim Jong-Un. Det finns bara ett politiskt parti och på varje röstsedel finns bara ett namn. Man lägger röstsedeln, utan något kuvert, i en box som står mitt i salen så att alla ser.",
        concepts: ["Diktatur", "Auktoritär", "Kim Jong-Un", "Censur"],
        mustKnow: ["Kännetecken för en diktatur", "Skillnaden mot en demokrati"],
        summary: ["En diktatur styrs genom rädsla och kontroll", "Det finns inga fria val"],
        test: [{ q: "Vem är diktator i Nordkorea?", a: "Kim Jong-Un" }],
        reasoning: "Varför har man val i diktaturer trots att alla vet vem som vinner?",
        application: "Hitta Nordkorea på en karta."
      },
      {
        title: "Sida 82: Aktivitet Propagandabild",
        page: "82",
        track: "Båda",
        core: true,
        text: "AKTIVITET - Analysera en propagandabild\n\nNordkorea är en diktatur. I huvudstaden Pyongyang står denna staty. Den visar inga kända personer. Tanken är att den ska visa hur hela folket står bakom partiets politik. Vi ska analysera statyn.\n\n1. Hur många personer är det och är det män eller kvinnor?\n2. Hur har konstnären valt att placera dem?\n3. Vad har de i sina händer?\n\nI Nordkorea brukar man säga att det finns tre samhällsklasser: arbetare (de som jobbar i industrin), bönder (de som sköter jordbruket) och tjänstemän (de som planerar och sitter på kontor och har lång utbildning).\n4. Vilken grupp tillhör personen till vänster, personen i mitten och personen till höger?\n5. Konstnären vill att statyn ska ge uttryck för att alla står enade bakom partiets politik. Ge exempel på hur han gjort för att skapa denna känsla.\n6. Lek med tanken att du får ändra något, t.ex. låta personerna titta åt olika håll. Hur hade det förändrat intrycket?",
        concepts: ["Propaganda", "Analys", "Samhällsklasser"],
        mustKnow: ["Vad propaganda är", "Att bilder kan användas för att styra tankar"],
        summary: ["Här analyseras en staty från en diktatur"],
        test: [{ q: "Vad kallas vinklad information från en stat?", a: "Propaganda" }],
        reasoning: "Varför vill diktatorer visa upp enade folk på bilder?",
        application: "Beskriv vad personerna på bilden håller i."
      },
      {
        title: "Sida 83: Hållplats 2 Demokrati",
        page: "83",
        track: "Båda",
        core: true,
        text: "SAMMANFATTNING\n\n• Vanligaste sättet att bestämma är den representativa demokratin.\n• Folkomröstningar är en form av direktdemokrati.\n• Ett parti måste få minst 4 procent av rösterna för att komma in i riksdagen.\n• Det normala i Sverige är att vi har en minoritetsregering.\n• I en diktatur kan ett parti även ta till våld för att behålla makten.\n• Nordkorea, Iran och Kina är exempel på mycket hårda diktaturer.\n• Ett auktoritärt land är ett land som inte är lika hårt och grymt styrt som en ren diktatur.\n\nVIKTIGA ORD\nvalrörelsen, valhemlighet, representativ demokrati, folkomröstningar, rådgivande, direktdemokrati, socialistiska partier, de röd-gröna, ett konservativt block, fyra-procents-spärren, mandat, minoritetsregering, votering, diktatur, auktoritära länder.",
        concepts: ["Mandat", "Votering", "Minoritet"],
        mustKnow: ["Alla sammanfattningspunkter", "De viktigaste orden"],
        summary: ["Här repeteras hur Sverige styrs och skillnaden mot diktatur"],
        test: [{ q: "Hur många procent krävs för riksdagen?", a: "4 procent" }],
        reasoning: "Förklara med egna ord: 'I en demokrati är oppositionen en nödvändighet, i en diktatur är oppositionen ett hot.'",
        application: "Para ihop rätt ord med rätt förklaring."
      }
    ]
  },
  {
    id: 6,
    title: "Sverige styrs – Riksdag, regering och EU",
    icon: "landmark",
    subject: "Demokrati",
    sections: [
      {
        title: "Sida 84: Så här styrs Sverige intro",
        page: "84",
        track: "Båda",
        core: true,
        text: "Så här styrs Sverige\n\nI det här kapitlet beskrivs hur Sverige styrs, det vill säga hur politiken fungerar. Sverige är en demokrati, men allt är ju inte felfritt. Demokrati är inget som riksdagen kan besluta om en gång för alla. Ett demokratiskt land kan alltid bli ännu bättre. Man brukar säga att demokratin måste erövras varje dag. Det handlar om att hålla sig själv informerad, att själv skapa sig en uppfattning, att lyssna på andras argument och så till slut själv ta ställning.\n\nRiksdagshuset ligger på Helgeandsholmen i Stockholm.\n\nLäs om\n- de olika grundlagarna.\n- riksdagens och regeringens viktigaste uppgifter.\n- vem som är Sveriges statschef och vad statschefen gör.\n- Sveriges kommuner och regioner.\n- varför EU bildades och på vilka område EU har makt.",
        concepts: ["Argument", "Information", "Ställningstagande"],
        mustKnow: ["Att demokrati kräver att man är aktiv", "Vart riksdagen ligger"],
        summary: ["Demokrati handlar om att delta och vara informerad"],
        test: [{ q: "Var ligger riksdagshuset?", a: "På Helgeandsholmen i Stockholm" }],
        reasoning: "Vad menas med att demokratin måste erövras varje dag?",
        application: "Hitta en bild på riksdagshuset."
      },
      {
        title: "Sida 85: Våra grundlagar",
        page: "85",
        track: "Båda",
        core: true,
        text: "Våra grundlagar\n\nFår politikerna fatta vilka beslut som helst? Nej, naturligtvis inte. Alla lagar och allt som beslutas av regeringen och riksdagen måste följa Sveriges grundlagar. Grundlagarna ger ramarna för hur demokratin ska fungera och är därför Sveriges viktigaste lagar. Här är de fyra grundlagarna:\n\n• Regeringsformen bestämmer hur Sverige ska styras. Främst gäller det vem eller vilka som har rätt att besluta i olika frågor. Regeringsformen innehåller också bestämmelser om mänskliga rättigheter.\n\n• Successionsordningen bestämmer vem som ska vara statschef i Sverige.\n\n• Tryckfrihetsförordningen bestämmer att det ska vara tryckfrihet och yttrandefrihet i böcker, tidningar och andra tryckta medier.\n\n• Yttrandefrihetsgrundlagen bestämmer att det ska vara yttrandefrihet även i radio, tv, filmer och webbplatser på internet. I kapitlet Medier och opinion kan du läsa om att censur är förbjudet för alla slags medier, tryckta och otryckta.",
        concepts: ["Regeringsformen", "Succession", "Tryckfrihet", "HBTQI"],
        mustKnow: ["Namnen på de fyra grundlagarna", "Vad varje grundlag handlar om"],
        summary: ["Grundlagarna är ramarna för demokratin och våra rättigheter"],
        test: [{ q: "Vilken grundlag styr vem som blir kung?", a: "Successionsordningen" }],
        reasoning: "Varför är det viktigt att grundlagar är svårare att ändra än andra lagar?",
        application: "Gör en lista på de fyra grundlagarna."
      },
      {
        title: "Sida 86: Vad gör riksdagen?",
        page: "86",
        track: "Båda",
        core: true,
        text: "Vad gör riksdagen?\n\nRiksdagsledamöterna pratar mycket, och tur är det, för man försöker komma överens. Riksdagen har fyra viktiga uppgifter:\n\n• Riksdagen bestämmer om lagar, \"stiftar lagar\". Skollagen bestämmer till exempel att alla barn i Sverige måste börja skolan det år de fyller sex.\n\n• Riksdagen utser statsminister. Talmannen, riksdagens ordförande, kommer med förslag som sedan riksdagens ledamöter röstar om.\n\n• Riksdagen bestämmer om statens finanser, det vill säga hur staten ska få in pengar (inkomster) och hur pengarna ska användas (utgifter). Det är riksdagen som bestämt om t.ex. moms och inkomstskatt.\n\n• Riksdagen kontrollerar regeringen, att regeringens ledamöter, statsråden, sköter sig. Varje torsdag är det frågestund i riksdagen.\n\nSkulle riksdagen och regeringen bli osams vinner alltid riksdagen! Riksdagen kan avsätta ett statsråd.",
        concepts: ["Stifta lagar", "Talman", "Statsråd", "Frågestund"],
        mustKnow: ["Riksdagens fyra huvuduppgifter", "Att riksdagen kontrollerar regeringen"],
        summary: ["Riksdagen bestämmer lagar och pengar"],
        test: [{ q: "Vem utser statsministern?", a: "Riksdagen (efter förslag från talmannen)" }],
        reasoning: "Varför har riksdagen mer makt än regeringen?",
        application: "Hitta på en fråga du skulle ställa till ett statsråd."
      },
      {
        title: "Sida 87: Vad gör regeringen?",
        page: "87",
        track: "Båda",
        core: true,
        text: "Vad gör regeringen?\n\nRegeringen består av drygt 20 politiker, som kallas statsråd eller ministrar. Viktigast är statsministern för det är statsministern som utser de andra statsråden. Ungefär hälften av statsråden är chef för ett departement, till exempel försvarsdepartementet och finansdepartementet. \n\nI regeringsformen står att regeringen \"styr\" Sverige. Vad gör då regeringen när den styr? Här är några exempel:\n\n• Regeringen skriver ihop förslag till riksdagen, propositioner. De viktigaste propositionerna varje år innehåller förslag till statens inkomster och utgifter. De kallas budgetpropositioner.\n\n• Regeringen skriver regler som kallas förordningar och som i detalj beskriver hur en lag ska tillämpas. \n\n• Regeringen ser också till att Skolverket, Skatteverket, Migrationsverket och andra myndigheter gör det de ska och följer riksdagens och regeringens beslut.\n\nSveriges första kvinnliga statsminister Magdalena Andersson framför sin regering 2021.",
        concepts: ["Minister", "Departement", "Proposition", "Förordning", "Myndighet"],
        mustKnow: ["Vem som leder regeringen", "Vad en proposition är", "Skillnaden på riksdag och regering"],
        summary: ["Regeringen genomför beslut och styr landets myndigheter"],
        test: [{ q: "Vad kallas regeringens förslag?", a: "Propositioner" }],
        reasoning: "Varför behövs det både en riksdag och en regering?",
        application: "Hitta namnet på en minister i dagens regering."
      },
      {
        title: "Sida 88: Statschefen",
        page: "88",
        track: "Båda",
        core: true,
        text: "Statschefen\n\nVår kung heter Carl XVI Gustaf. Kungen är Sveriges statschef. När kronprinsessan Victoria tar vid blir hon vår drottning och Sveriges statschef. Länder som har en statschef som ärver sitt jobb kallas monarkier. Motsatsen är republiker som har en statschef som väljs (president).\n\nKungen har ingen politisk makt. Man brukar säga att statschefen är en symbol för Sverige. Det är statschefen som tar emot utländska statschefer när de kommer till Sverige. Han åker också ofta utomlands för att besöka andra länder och gör på så sätt reklam för Sverige. Kungen får inte lägga sig i politiken. Statschefen har rösträtt, men av gammal tradition röstar ingen i kungahuset.\n\nKungahusets medlemmar är de enda som inte har religionsfrihet i Sverige. Kungen måste vara protestant. Om kronprinsessan Victoria skulle byta religion får hon inte fortsätta vara kronprinsessa.",
        concepts: ["Statschef", "Monarki", "Republik", "Religionsfrihet", "Symbol"],
        mustKnow: ["Att kungen inte har politisk makt", "Skillnaden på monarki och republik", "Att kungen måste vara protestant"],
        summary: ["Sverige är en monarki där kungen är vår statschef och symbol"],
        test: [{ q: "Vad heter Sveriges kung?", a: "Carl XVI Gustaf" }],
        reasoning: "Varför tror du att kungen inte får lägga sig i politiken?",
        application: "Ta reda på vad Estelle har för framtida jobb."
      },
      {
        title: "Sida 89: Hållplats 1 Sverige styrs",
        page: "89",
        track: "Båda",
        core: true,
        text: "SAMMANFATTNING\n\n• Regeringsformen och de övriga tre grundlagarna bestämmer vem som ska bestämma i Sverige.\n• Riksdagens 349 ledamöter är svenska folkets representanter och bestämmer för folket.\n• Riksdagen utser statsminister, stiftar lagar och beslutar om statens finanser, propositioner.\n• Riksdagen kontrollerar regeringen och kan till och med avsätta regeringen.\n• Regeringens medlemmar kallas statsråd eller ministrar.\n• Sverige är en monarki och statschef är vår kung Carl XVI Gustaf.\n\nVIKTIGA ORD\ngrundlag, statschef, regeringsformen, successionsordningen, tryckfrihetsförordningen, yttrandefrihetsgrundlagen, talmannen, statsråd, proposition, myndighet, monarki, republik, president.",
        concepts: ["Regeringsformen", "Sammanfattning", "Grundlag"],
        mustKnow: ["Alla punkter", "Alla viktiga ord"],
        summary: ["Här repeteras hur Sverige styrs på riksnivå"],
        test: [{ q: "Hur många sitter i riksdagen?", a: "349 ledamöter" }],
        reasoning: "Vilken är riksdagens viktigaste uppgift enligt dig?",
        application: "Välj ett ord och förklara det för bänkkompisen."
      },
      {
        title: "Sida 90: Kommuner",
        page: "90",
        track: "Båda",
        core: true,
        text: "Kommuner\n\nSverige är indelat i 290 kommuner. En del kommuner kallar sig städer men alla styrs på samma sätt enligt kommunallagen. Kiruna är störst till ytan, Sundbyberg minst.\n\nVarje kommun har ett kommunfullmäktige med politiker som väljs vart fjärde år. Kommunfullmäktige är kommunens \"riksdag\". Det finns också en \"regering\" i kommunen som kallas kommunstyrelsen. Där sitter kommunens främsta politiker från de olika partierna.\n\nKommunfullmäktige bestämmer över mycket som är viktigt för dig:\n\n• Hur hög ska kommunalskatten vara? Ca 32 kronor per intjänad hundralapp.\n\n• Hur många grundskolor och förskolor ska finnas? Vad får maten kosta?\n\n• Hur ska äldreomsorgen se ut i kommunen?\n\n• Hur mycket pengar ska man använda till snöröjning och lagning av vägar?\n\n• Hur många fotbollsplaner ska det finnas? \n\nDet är viktigt att invånarna diskuterar dessa frågor så att de ser vad partierna tycker.",
        concepts: ["Kommun", "Kommunfullmäktige", "Kommunalskatt", "Opposition"],
        mustKnow: ["Att det finns 290 kommuner", "Vad kommunfullmäktige beslutar om"],
        summary: ["Kommunen sköter det som är närmast din vardag (skola, vägar)"],
        test: [{ q: "Vad kallas kommunens riksdag?", a: "Kommunfullmäktige" }],
        reasoning: "Varför får skatten variera mellan olika kommuner?",
        application: "Kolla upp vem som leder din kommun."
      },
      {
        title: "Sida 91: Aktivitet Kommunens uppgifter",
        page: "91",
        track: "Båda",
        core: true,
        text: "AKTIVITET - Kommunens uppgifter\n\nHeba är 12 år och Gunnar 82. Under tiden som du läser ska du fundera över vad det är kommunen de bor i ordnar.\n\nHeba åker skolbuss, går till biblioteket, spelar fotboll på plogad väg. Hon bröt armen och åkte till sjukhuset.\n\nGunnar har svår värk och bor på ett serviceboende. Varje morgon kommer hemtjänsten och hjälper honom.\n\nKommunens ansvar:\n- äldreomsorg (Gunnar)\n- barnomsorg, förskola (Heba)\n- renhållning och avfallshantering (Båda)\n- räddningstjänst (Båda)\n- vatten och avlopp (Båda)\n- bibliotek (Heba)\n- grundskola och gymnasium (Heba)\n- vägar, snöröjning (Båda)\n\nFrivilligt:\n- fritidsverksamhet\n- kulturverksamhet utöver bibliotek",
        concepts: ["Service", "Äldreomsorg", "Skolbuss", "Hemtjänst"],
        mustKnow: ["Skillnaden på obligatoriska och frivilliga uppgifter", "Vem som sköter sjukhuset (regionen)"],
        summary: ["Här får eleverna lära sig vad kommunen gör för folk i olika åldrar"],
        test: [{ q: "Är bibliotek en obligatorisk uppgift för kommunen?", a: "Ja" }],
        reasoning: "Vilken service från kommunen använder du mest i din vardag?",
        application: "Sätt ett X för vad du använt idag i kommunens lista."
      },
      {
        title: "Sida 92: Regioner",
        page: "92",
        track: "Båda",
        core: true,
        text: "Regioner\n\nSverige är också indelat i 21 regioner som bestämmer över sjukvården och hälsovården i länet, men också om kollektivtrafik och vägar. Man säger att regionen har ett regionalt utvecklingsansvar.\n\nDet är politiker som bestämmer i regionen, och de väljs till regionfullmäktige vart fjärde år. Regionerna får sina pengar mest från skatten.\n\nVarje region är också ett län med en länshuvudstad. I varje län finns en länsstyrelse med en landshövding som chef. I länsstyrelsen arbetar tjänstemän som på regeringens uppdrag kontrollerar att lagarna följs i länet, t.ex. hur lantbrukare sköter djurhållningen eller hur affärer förvarar livsmedel.\n\nRegionerna bedriver inte bara sjukvård utan också rehabilitering och träning av patienter. Här ser vi en fysioterapeut i arbete.",
        concepts: ["Region", "Län", "Landshövding", "Länsstyrelse"],
        mustKnow: ["Att det finns 21 regioner", "Regionens huvuduppgifter som sjukvård"],
        summary: ["Regionerna ansvarar för frågor som är för stora för en enda kommun"],
        test: [{ q: "Vad är regionernas viktigaste uppgift?", a: "Sjukvård och hälsovård" }],
        reasoning: "Varför sköts inte sjukvården av varje kommun för sig?",
        application: "Ta reda på vad din landshövding heter."
      },
      {
        title: "Sida 93: EU",
        page: "93",
        track: "Båda",
        core: true,
        text: "EU\n\nEU startade efter andra världskriget som ett fredsprojekt. Man tänkte så här: länder som träffas och pratar, ibland till och med grälar, börjar inte kriga. Dessutom fritt kunna handla med varandra.\n\nEuropeiska Unionen består av 27 länder. Sverige gick med 1995. EU:s \"huvudstad\" är Bryssel i Belgien. Några länder står i kö för att bli medlemmar, de kallas kandidatländer. De ska vara demokratier, respektera mänskliga rättigheter och ha ordning på sin ekonomi. Island, Norge och Schweiz är inte med i EU.\n\nSamarbete mellan länderna\nMedlemsländer låter EU bestämma en hel del om miljö och ekonomi. EU kan tvinga ett land att stänga miljöfarliga fabriker. EU hjälper också till så att fattiga länder får råd att göra fabriker miljövänliga. Bönder får pengar från EU men måste följa regler. 2022 förbjöds bekämpningsmedlet Roundup i hela EU.",
        concepts: ["EU", "Bryssel", "Kandidatländer", "Fredsprojekt"],
        mustKnow: ["Varför EU bildades", "Krav på att få gå med i EU"],
        summary: ["EU är ett samarbete för fred och handel mellan 27 länder"],
        test: [{ q: "I vilket land ligger Bryssel?", a: "Belgien" }],
        reasoning: "Varför är det bra att EU kan bestämma över miljölagar i alla länder?",
        application: "Hitta tre länder på kartan som inte är med i EU."
      },
      {
        title: "Sida 94: Aktivitet Skapa opinion",
        page: "94",
        track: "Båda",
        core: true,
        text: "EU och svenska lagar\nSveriges riksdag måste rätta sig efter EU in många frågor. Även kommunerna måste följa EU:s lagar. En kommun får t.ex. inte ge pengar till ett företag som inte klarar konkurrensen.\n\nAKTIVITET - Hur kan ni i klassen skapa opinion?\n\n1. Välj ett ämne (t.ex. för dyrt padel, inget ridhus, mörka vägar).\n2. Välj bäst sätt:\nA. Skriv till en politiker (kommunstyrelsens ordförande).\nB. Facebook-grupper.\nC. Insändare i lokaltidningen.\nD. Medborgarförslag (gäller även barn utan rösträtt).\n\nFormulera frågan tydligt och välj sätt att nå fram till beslutsfattare.",
        concepts: ["Opinion", "Beslutsfattare", "Medborgarförslag"],
        mustKnow: ["Att man kan påverka utan rösträtt", "Sätt att bilda opinion"],
        summary: ["Här får eleverna öva på praktisk demokrati och påverkan"],
        test: [{ q: "Får barn skriva medborgarförslag?", a: "Ja" }],
        reasoning: "Vilket metod tror du fungerar bäst för att nå en politiker idag?",
        application: "Skriv en rubrik till ett medborgarförslag för din skola."
      },
      {
        title: "Sida 95: Hållplats 2 Sverige styrs",
        page: "95",
        track: "Båda",
        core: true,
        text: "SAMMANFATTNING\n\n• Sveriges 290 kommuner har ett kommunfullmäktige valda av invånarna.\n• Kommunens \"regering\" kallas kommunstyrelsen.\n• Kommunalskatten varierar mellan kommuner.\n• Sveriges 21 regioner styrs av regionfullmäktige.\n• Regionerna bestämmer om sjukvården och folktandvården.\n• Varje region är också ett län med en landshövding.\n• EU bestämmer lagar som alla medlemsländer måste rätta sig efter.\n\nVIKTIGA ORD\nkommuner, regioner, kommunfullmäktige, regionalt utvecklingsansvar, kommunstyrelsen, regionfullmäktige, kommunalskatt, län, kommunallagen, länsstyrelse, Europeiska Unionen, kandidatländer, landshövding.",
        concepts: ["Sammanfattning", "Begrepp"],
        mustKnow: ["Alla sammanfattningspunkter", "Alla ord i listan"],
        summary: ["Här repeteras det lokala och regionala styret samt EU"],
        test: [{ q: "Vad sköter regionerna i Sverige?", a: "Sjukvård och kollektivtrafik" }],
        reasoning: "Varför är det viktigt att veta vem som bestämmer över skolan?",
        application: "Välj ett ord från listan och rita en bild av det."
      }
    ]
  }
];
